### ISSUE TITLE
availability

### ISSUE THREAD

**Issue by cortesimone** [tomslee/airbnb-data-collection#24]
Hi,
it is not clear to me how to gather availability for a given room. 
Thanks,
S.

**Comment by tomslee** [comment]
Hi,

I do not have good availability data for a room. Inside Airbnb collects calendar data which shows data on which a room is available, but they also do not show actual occupancy.  AirDNA claims to collect occupancy, but it's also an estimate.

The best I can do is use the number of reviews as a proxy. Recent research suggests that about 55% of visits leave a review, so that's all I go by. It is not going to be accurate for an individual room of course, but I think it's reasonable for tracking aggregate trends in occupancy.

Tom

**Comment by cortesimone** [comment]
hi Tom,
it appears to me there is a calendar_month method in the undocumented airbnb API: https://www.airbnb.com/api/v2/calendar_months. Are you using this?

you just have a way to tell if the room is booked or not, and do not have any data on how many persons are sleeping in the room? is that what you are saying?

Simone.

**Comment by joao** [comment]
Hi,

Hope Tom doesn’t mind I answer this.

Tom’s project isn’t using the undocumented Airbnb API but scraping the
website. To use the undocumented API you have to supply your user
credentials and they can detect the huge amount of requests, probably
suspending your account for abuse.
Even with scraping you have to use a set amount of proxys, with different
IPs, so they don’t block you.

The information of how many people are going to stay in a Airbnb property
is not public. Data resellers just do an estimation based on the public
rental information.

- @joao

**Comment by cortesimone** [comment]
Thanks for the info!
